### PR TITLE
Moved build dependencies to devDependencies

### PR DESCRIPTION
**Pull request by YasserAA**
This fix is to reduce the size of the node modules by moving build dependencies to devDependencies.
Related issue https://github.com/facebook/facebook-nodejs-business-sdk/issues/52

### CODE REVIEW

**Comment by michaelwclark** [comment]
@YasserAA  have you signed a CLA? If not, I can reproduce this and do the PR from my end. We are dependant on this fix before we are in full production mode on our serverless project.

**Comment by TheLudd** [comment]
Should not also everything related to eslint, gulp and jshint also be moved to devDependencies?

@michaelwclark If you can speed this up with your own PR, please do. This causes problems for us as well.

**Comment by michaelwclark** [comment]
@bertero  None have since May. The dev cycle of this project is too slow for me. I'm forking and republishing under my company scope. I'll update everyone when this is finished in the next day or so. Hopefully this will get the attention of FB devs and perhaps allow me to get on as maintainer of this project. At that point I'll be updating weekly here, until then I will be doing so on our fork.

**Comment by YasserAA** [comment]
Sorry for the late reply, I have signed the CLA now.

**Comment by michaelwclark** [comment]
I have decided to publish this under our company scope. I will maintain PRs weekly to our repo and will PR back in to this master at the same frequency until maintainers here are able to keep up with community demand.  https://github.com/denimlabs/facebook-nodejs-business-sdk
`npm i @denimlabs/facebook-nodejs-business-sdk`

**Comment by codytwinton** [comment]
Thank you all for your patience. We're a small team working on the SDKs, but we're doing our best to move these SDKs forward.

I'll merge this into our internal repo and it should be available for the next release.

**Comment by TheLudd** [comment]
@codytwinton @YasserAA please see my comment regarding this PR before merging:

> Should not also everything related to eslint, gulp and jshint also be moved to devDependencies?

All these dependencies should be moved, they also cause problems when they are located under regular dependencies.

**Comment by YasserAA** [comment]
@TheLudd They are in devDependencies, check the code. 
`"dependencies":  {
    "mixwith": "~0.1.1",
    "request": "^2.81.0",
    "request-promise": "~4.1.1",
  },`

**Comment by TheLudd** [comment]
Ok, looks good for me as well then.

**Comment by michaelwclark** [comment]
@TheLudd Should be g2g, Iv'e been using this PR in my fork for several weeks without issue. As far as I know we were just waiting on you guys to do release.

**Comment by TheLudd** [comment]
@michaelwclark Do you have a public released version of that fork that I can use as well?
PS I am not a part of Facebook and not involved in merge/release of this.

**Comment by michaelwclark** [comment]
@TheLudd  yes sir. sorry I just noticed this. `npm i @denimlabs/facebook-nodejs-business-sdk`
https://github.com/denimlabs/facebook-nodejs-business-sdk

**Comment by michaelwclark** [comment]
@YasserAA  this should be closed. The team has since implimented this in current build. @codytwinton  @bertero  or @YasserAA  please close this.

**Pull request closed without merging**
